<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.CloseTradeRequest</code>
 */
class CloseTradeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     */
    private $ticket = 0;
    /**
     * Generated from protobuf field <code>int32 volume = 2;</code>
     */
    private $volume = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ticket
     *     @type int $volume
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     * @return int
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTicket($var)
    {
        GPBUtil::checkInt32($var);
        $this->ticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 2;</code>
     * @return int
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt32($var);
        $this->volume = $var;

        return $this;
    }

}

