<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.DeleteUserRequest</code>
 */
class DeleteUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    private $token = '';
    /**
     * Generated from protobuf field <code>int32 login = 2;</code>
     */
    private $login = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type int $login
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 login = 2;</code>
     * @return int
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Generated from protobuf field <code>int32 login = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkInt32($var);
        $this->login = $var;

        return $this;
    }

}

