<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.FundsInfo</code>
 */
class FundsInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 login = 1;</code>
     */
    private $login = 0;
    /**
     * Generated from protobuf field <code>double amount = 2;</code>
     */
    private $amount = 0.0;
    /**
     * Generated from protobuf field <code>int32 is_credit = 3;</code>
     */
    private $is_credit = 0;
    /**
     * Generated from protobuf field <code>string comment = 4;</code>
     */
    private $comment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $login
     *     @type float $amount
     *     @type int $is_credit
     *     @type string $comment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 login = 1;</code>
     * @return int
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Generated from protobuf field <code>int32 login = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkInt32($var);
        $this->login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 2;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 is_credit = 3;</code>
     * @return int
     */
    public function getIsCredit()
    {
        return $this->is_credit;
    }

    /**
     * Generated from protobuf field <code>int32 is_credit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIsCredit($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_credit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 4;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

}

