<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.FundsResponse</code>
 */
class FundsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double balance = 1;</code>
     */
    private $balance = 0.0;
    /**
     * Generated from protobuf field <code>double credit = 2;</code>
     */
    private $credit = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $balance
     *     @type float $credit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double balance = 1;</code>
     * @return float
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>double balance = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double credit = 2;</code>
     * @return float
     */
    public function getCredit()
    {
        return $this->credit;
    }

    /**
     * Generated from protobuf field <code>double credit = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCredit($var)
    {
        GPBUtil::checkDouble($var);
        $this->credit = $var;

        return $this;
    }

}

