<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.OpenTradeRequest</code>
 */
class OpenTradeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 login = 1;</code>
     */
    private $login = 0;
    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     */
    private $symbol = '';
    /**
     * Generated from protobuf field <code>.api_pb.Cmd cmd = 3;</code>
     */
    private $cmd = 0;
    /**
     * Generated from protobuf field <code>double price = 4;</code>
     */
    private $price = 0.0;
    /**
     * Generated from protobuf field <code>int32 slippage = 5;</code>
     */
    private $slippage = 0;
    /**
     * Generated from protobuf field <code>double sl = 6;</code>
     */
    private $sl = 0.0;
    /**
     * Generated from protobuf field <code>double tp = 7;</code>
     */
    private $tp = 0.0;
    /**
     * Generated from protobuf field <code>int32 volume = 8;</code>
     */
    private $volume = 0;
    /**
     * Generated from protobuf field <code>string comment = 9;</code>
     */
    private $comment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $login
     *     @type string $symbol
     *     @type int $cmd
     *     @type float $price
     *     @type int $slippage
     *     @type float $sl
     *     @type float $tp
     *     @type int $volume
     *     @type string $comment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 login = 1;</code>
     * @return int
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Generated from protobuf field <code>int32 login = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkInt32($var);
        $this->login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api_pb.Cmd cmd = 3;</code>
     * @return int
     */
    public function getCmd()
    {
        return $this->cmd;
    }

    /**
     * Generated from protobuf field <code>.api_pb.Cmd cmd = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCmd($var)
    {
        GPBUtil::checkEnum($var, \MT4ManagerApi\Cmd::class);
        $this->cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slippage = 5;</code>
     * @return int
     */
    public function getSlippage()
    {
        return $this->slippage;
    }

    /**
     * Generated from protobuf field <code>int32 slippage = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSlippage($var)
    {
        GPBUtil::checkInt32($var);
        $this->slippage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sl = 6;</code>
     * @return float
     */
    public function getSl()
    {
        return $this->sl;
    }

    /**
     * Generated from protobuf field <code>double sl = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setSl($var)
    {
        GPBUtil::checkDouble($var);
        $this->sl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tp = 7;</code>
     * @return float
     */
    public function getTp()
    {
        return $this->tp;
    }

    /**
     * Generated from protobuf field <code>double tp = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTp($var)
    {
        GPBUtil::checkDouble($var);
        $this->tp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 8;</code>
     * @return int
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt32($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 9;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

}

