<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.TradeInfo</code>
 */
class TradeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     */
    private $ticket = 0;
    /**
     * Generated from protobuf field <code>int32 login = 2;</code>
     */
    private $login = 0;
    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     */
    private $symbol = '';
    /**
     * Generated from protobuf field <code>int32 digits = 4;</code>
     */
    private $digits = 0;
    /**
     * Generated from protobuf field <code>.api_pb.Cmd cmd = 5;</code>
     */
    private $cmd = 0;
    /**
     * Generated from protobuf field <code>int32 volume = 6;</code>
     */
    private $volume = 0;
    /**
     * Generated from protobuf field <code>int32 open_time = 7;</code>
     */
    private $open_time = 0;
    /**
     * Generated from protobuf field <code>int32 state = 8;</code>
     */
    private $state = 0;
    /**
     * Generated from protobuf field <code>double open_price = 9;</code>
     */
    private $open_price = 0.0;
    /**
     * Generated from protobuf field <code>double sl = 10;</code>
     */
    private $sl = 0.0;
    /**
     * Generated from protobuf field <code>double tp = 11;</code>
     */
    private $tp = 0.0;
    /**
     * Generated from protobuf field <code>int32 close_time = 12;</code>
     */
    private $close_time = 0;
    /**
     * Generated from protobuf field <code>int32 expiration = 13;</code>
     */
    private $expiration = 0;
    /**
     * Generated from protobuf field <code>double commission = 14;</code>
     */
    private $commission = 0.0;
    /**
     * Generated from protobuf field <code>double close_price = 15;</code>
     */
    private $close_price = 0.0;
    /**
     * Generated from protobuf field <code>double profit = 16;</code>
     */
    private $profit = 0.0;
    /**
     * Generated from protobuf field <code>int32 magic = 17;</code>
     */
    private $magic = 0;
    /**
     * Generated from protobuf field <code>string comment = 18;</code>
     */
    private $comment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ticket
     *     @type int $login
     *     @type string $symbol
     *     @type int $digits
     *     @type int $cmd
     *     @type int $volume
     *     @type int $open_time
     *     @type int $state
     *     @type float $open_price
     *     @type float $sl
     *     @type float $tp
     *     @type int $close_time
     *     @type int $expiration
     *     @type float $commission
     *     @type float $close_price
     *     @type float $profit
     *     @type int $magic
     *     @type string $comment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     * @return int
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTicket($var)
    {
        GPBUtil::checkInt32($var);
        $this->ticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 login = 2;</code>
     * @return int
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Generated from protobuf field <code>int32 login = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkInt32($var);
        $this->login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 digits = 4;</code>
     * @return int
     */
    public function getDigits()
    {
        return $this->digits;
    }

    /**
     * Generated from protobuf field <code>int32 digits = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDigits($var)
    {
        GPBUtil::checkInt32($var);
        $this->digits = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api_pb.Cmd cmd = 5;</code>
     * @return int
     */
    public function getCmd()
    {
        return $this->cmd;
    }

    /**
     * Generated from protobuf field <code>.api_pb.Cmd cmd = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCmd($var)
    {
        GPBUtil::checkEnum($var, \MT4ManagerApi\Cmd::class);
        $this->cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 6;</code>
     * @return int
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt32($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 open_time = 7;</code>
     * @return int
     */
    public function getOpenTime()
    {
        return $this->open_time;
    }

    /**
     * Generated from protobuf field <code>int32 open_time = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setOpenTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->open_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 state = 8;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>int32 state = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkInt32($var);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double open_price = 9;</code>
     * @return float
     */
    public function getOpenPrice()
    {
        return $this->open_price;
    }

    /**
     * Generated from protobuf field <code>double open_price = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setOpenPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->open_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sl = 10;</code>
     * @return float
     */
    public function getSl()
    {
        return $this->sl;
    }

    /**
     * Generated from protobuf field <code>double sl = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setSl($var)
    {
        GPBUtil::checkDouble($var);
        $this->sl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tp = 11;</code>
     * @return float
     */
    public function getTp()
    {
        return $this->tp;
    }

    /**
     * Generated from protobuf field <code>double tp = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setTp($var)
    {
        GPBUtil::checkDouble($var);
        $this->tp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 close_time = 12;</code>
     * @return int
     */
    public function getCloseTime()
    {
        return $this->close_time;
    }

    /**
     * Generated from protobuf field <code>int32 close_time = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCloseTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->close_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expiration = 13;</code>
     * @return int
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>int32 expiration = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkInt32($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double commission = 14;</code>
     * @return float
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * Generated from protobuf field <code>double commission = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setCommission($var)
    {
        GPBUtil::checkDouble($var);
        $this->commission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double close_price = 15;</code>
     * @return float
     */
    public function getClosePrice()
    {
        return $this->close_price;
    }

    /**
     * Generated from protobuf field <code>double close_price = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setClosePrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->close_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double profit = 16;</code>
     * @return float
     */
    public function getProfit()
    {
        return $this->profit;
    }

    /**
     * Generated from protobuf field <code>double profit = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setProfit($var)
    {
        GPBUtil::checkDouble($var);
        $this->profit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 magic = 17;</code>
     * @return int
     */
    public function getMagic()
    {
        return $this->magic;
    }

    /**
     * Generated from protobuf field <code>int32 magic = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setMagic($var)
    {
        GPBUtil::checkInt32($var);
        $this->magic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 18;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

}

