<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.UpdateTradeRequest</code>
 */
class UpdateTradeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     */
    private $ticket = 0;
    /**
     * Generated from protobuf field <code>double price = 4;</code>
     */
    private $price = 0.0;
    /**
     * Generated from protobuf field <code>double sl = 6;</code>
     */
    private $sl = 0.0;
    /**
     * Generated from protobuf field <code>double tp = 7;</code>
     */
    private $tp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ticket
     *     @type float $price
     *     @type float $sl
     *     @type float $tp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     * @return int
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * Generated from protobuf field <code>int32 ticket = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTicket($var)
    {
        GPBUtil::checkInt32($var);
        $this->ticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sl = 6;</code>
     * @return float
     */
    public function getSl()
    {
        return $this->sl;
    }

    /**
     * Generated from protobuf field <code>double sl = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setSl($var)
    {
        GPBUtil::checkDouble($var);
        $this->sl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tp = 7;</code>
     * @return float
     */
    public function getTp()
    {
        return $this->tp;
    }

    /**
     * Generated from protobuf field <code>double tp = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTp($var)
    {
        GPBUtil::checkDouble($var);
        $this->tp = $var;

        return $this;
    }

}

