<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace MT4ManagerApi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api_pb.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only.
     *
     * Generated from protobuf field <code>int32 login = 1;</code>
     */
    private $login = 0;
    /**
     * Generated from protobuf field <code>string group = 2;</code>
     */
    private $group = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int32 enabled = 4;</code>
     */
    private $enabled = 0;
    /**
     * Generated from protobuf field <code>int32 leverage = 5;</code>
     */
    private $leverage = 0;
    /**
     * Output only.
     *
     * Generated from protobuf field <code>double balance = 6;</code>
     */
    private $balance = 0.0;
    /**
     * Output only.
     *
     * Generated from protobuf field <code>double credit = 7;</code>
     */
    private $credit = 0.0;
    /**
     * Generated from protobuf field <code>int32 agent_account = 8;</code>
     */
    private $agent_account = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $login
     *           Output only.
     *     @type string $group
     *     @type string $name
     *     @type int $enabled
     *     @type int $leverage
     *     @type float $balance
     *           Output only.
     *     @type float $credit
     *           Output only.
     *     @type int $agent_account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only.
     *
     * Generated from protobuf field <code>int32 login = 1;</code>
     * @return int
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Output only.
     *
     * Generated from protobuf field <code>int32 login = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkInt32($var);
        $this->login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group = 2;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Generated from protobuf field <code>string group = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 enabled = 4;</code>
     * @return int
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Generated from protobuf field <code>int32 enabled = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkInt32($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 leverage = 5;</code>
     * @return int
     */
    public function getLeverage()
    {
        return $this->leverage;
    }

    /**
     * Generated from protobuf field <code>int32 leverage = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLeverage($var)
    {
        GPBUtil::checkInt32($var);
        $this->leverage = $var;

        return $this;
    }

    /**
     * Output only.
     *
     * Generated from protobuf field <code>double balance = 6;</code>
     * @return float
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Output only.
     *
     * Generated from protobuf field <code>double balance = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Output only.
     *
     * Generated from protobuf field <code>double credit = 7;</code>
     * @return float
     */
    public function getCredit()
    {
        return $this->credit;
    }

    /**
     * Output only.
     *
     * Generated from protobuf field <code>double credit = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setCredit($var)
    {
        GPBUtil::checkDouble($var);
        $this->credit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 agent_account = 8;</code>
     * @return int
     */
    public function getAgentAccount()
    {
        return $this->agent_account;
    }

    /**
     * Generated from protobuf field <code>int32 agent_account = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAgentAccount($var)
    {
        GPBUtil::checkInt32($var);
        $this->agent_account = $var;

        return $this;
    }

}

